# Generated by Django 4.2.3 on 2023-07-07 17:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=800)),
                ('created_at', models.TimeField(default=django.utils.timezone.now)),
                ('updated_at', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=800)),
                ('created_at', models.TimeField(default=django.utils.timezone.now)),
                ('updated_at', models.TimeField(default=django.utils.timezone.now)),
                ('experiment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.experiments')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=85)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.TimeField(default=django.utils.timezone.now)),
                ('updated_at', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('created_at', models.TimeField(default=django.utils.timezone.now)),
                ('updated_at', models.TimeField(default=django.utils.timezone.now)),
                ('sample_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.samples')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.TimeField(default=django.utils.timezone.now)),
                ('updated_at', models.TimeField(default=django.utils.timezone.now)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.tests')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('lider_id', models.IntegerField()),
                ('created_at', models.TimeField(default=django.utils.timezone.now)),
                ('updated_at', models.TimeField(default=django.utils.timezone.now)),
                ('users_id', models.ManyToManyField(auto_created=True, to='lab.users')),
            ],
        ),
        migrations.AddField(
            model_name='experiments',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.groups'),
        ),
    ]
