# Generated by Django 4.2.3 on 2023-07-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_alter_experiments_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='users_id',
            field=models.ManyToManyField(null=True, to='lab.users'),
        ),
    ]
