# Generated by Django 4.2.3 on 2023-07-09 22:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_alter_groups_users_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_to', models.IntegerField()),
                ('token', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.users')),
            ],
        ),
    ]
