# Generated by Django 4.2.3 on 2023-07-09 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_invitations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitations',
            name='_from',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='invitations',
            name='_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.users'),
        ),
    ]
